### ISSUE TITLE
what's the k? or what the CompleteKPartiteGraph do?

### ISSUE THREAD

**Issue by tjuwangyinghui** [cqql/graph2gauss-pytorch#1]
![image](https://user-images.githubusercontent.com/22472194/89117156-3c67ab80-d4ce-11ea-89f7-766125aaed97.png)

**Comment by martenlienen** [comment]
It is bad naming. The `k` in the graph is the number of partitions whereas `k` in this code is the other node in the edge `(j, k)`.
